version: '3'
services:
  postgres:
    image: postgres:9.3
    ports:
        - "5432:5432"
    env_file:
      - .env
    volumes:
        - postgres-data:/var/lib/postgresql/data
  jira:
    build: .
    image: webinventions/atlassian-jira:7.12.3
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    volumes:
      - jira-data:/var/atlassian/jira/data
volumes:
  postgres-data:
  jira-data: