version: '3'
services:
  postgres:
    image: postgres:9.3
    ports:
        - "${BIND_IP}:5432:5432"
    environment:
        - POSTGRES_USER=jira
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-jira}
        - POSTGRES_DB=jira
        - TZ={TZ:-UTC}
    volumes:
        - postgres-data:/var/lib/postgresql/data
  jira:
    build: .
    image: webinventions/atlassian-jira:7.6.1
    ports:
      - "${BIND_IP}:8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - jira-data:/var/atlassian/jira/data
volumes:
  postgres-data:
  jira-data: